availability_zone  = "us-east-1a"
instance_type      = "t2.nano"
key_name           = "Laptop"
aws_region         = "us-east-1"
vpc_name           = "VPC"
vpc_cidr           = "10.35.0.0/16"
public_subnet_cidr = "10.35.1.0/24"
environment        = "dev"
